Abstract config from build scripts
18F/identity-idva-orchestration pull request #106
Opened 2021-12-21 20:11 UTC by dzaslavskiy

2021-12-21 21:06 UTC, folksgl requested changes
Great PR overall. It'll be really nice to finally be able to separate configuration from code here.

2021-12-21 21:06 UTC, folksgl commented on services.json
> +{
This json structure is slightly unintuitive to me, could you explain the reasoning behind it? To me, I see the services being the outer keys, and the environments being under `plan` similar to the following:

```json
"db": {
  "name": "sk-postgres",
  "service": "aws-rds",
  "plan": {
    "dev": "small-psql",
    "test": "small-psql",
    "prod": "large-psql"
  }
}
```

This ensures that only the area intended to change between environments (the amount of hardware) is capable of drifting between dev/test/prod. If there are other reasons behind the current structure, let me know.

2021-12-21 22:12 UTC, dzaslavskiy commented on services.json
> +{
thats a good point

2021-12-22 16:44 UTC, folksgl approved these changes

2021-12-22 17:17 UTC, merged