Sequence by master workflow
18F/identity-idva-orchestration pull request #94
Opened 2021-12-17 06:05 UTC by dzaslavskiy

2021-12-17 20:35 UTC, folksgl commented
Love the `cancel-deployment` step on failure. That should really help the dev cycle if things don't work the first time around.

2021-12-17 20:37 UTC, folksgl submitted a review, later dismissed

2021-12-20 15:00 UTC, folksgl requested changes
SK `.github/` folder is getting large/complex enough to likely deserve its own README. What's here now is hard enough for us to keep track of, not to mention anyone new to the project. Think you could add an overview for our actions/processes/workflows?

2021-12-20 15:00 UTC, folksgl commented on .github/workflows/deploy-ALL-connectors-1.yaml
> +          check-regexp: (run-manifest|run-dbconfigs)
Can likely be shortened to
```suggestion
          check-regexp: run-(manifest|dbconfigs)
```

2021-12-20 15:00 UTC, folksgl commented on .github/workflows/deploy-ALL-connectors-0.yaml
> +          check-regexp: (run-manifest|run-dbconfigs)
See other comment on shorter regex

2021-12-20 21:25 UTC, dzaslavskiy commented on .github/workflows/deploy-ALL-connectors-1.yaml
> +          check-regexp: (run-manifest|run-dbconfigs)
shorter maybe but I think as it currently is more readable

2021-12-20 21:26 UTC, dzaslavskiy commented
Added a basic readme and long with smtp and s3.

2021-12-21 19:58 UTC, folksgl approved these changes

2021-12-21 20:00 UTC, merged